# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Zlib
version:      1.04
version_from: Zlib.pm
installdirs:  site
requires:
    Compress::Zlib:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
